### ISSUE TITLE
bug: Flask Response Validation Error Results in Exception, Unintended 500 content

### ISSUE THREAD

**Issue by nossonCotlar** [0b01001001/spectree#347]
### Describe the bug

When a Flask endpoint returns a response that does not adhere to the specified Pydantic model for that route/code, an exception is raised resulting in Flask being unable to respond with the intended data. Example:
```
Traceback (most recent call last):
  File "/home/ncotlar/MF/venv/lib/python3.10/site-packages/spectree/plugins/flask_plugin.py", line 217, in validate
    response_validation_result = validate_response(
  File "/home/ncotlar/MF/venv/lib/python3.10/site-packages/spectree/plugins/base.py", line 174, in validate_response
    validator(final_response_payload)
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for TestResponse
age
  value is not a valid integer (type=type_error.integer)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ncotlar/MF/venv/lib/python3.10/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ncotlar/MF/venv/lib/python3.10/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/home/ncotlar/MF/venv/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ncotlar/MF/venv/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ncotlar/MF/venv/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ncotlar/MF/venv/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/ncotlar/MF/venv/lib/python3.10/site-packages/spectree/spec.py", line 181, in sync_validate
    return self.backend.validate(
  File "/home/ncotlar/MF/venv/lib/python3.10/site-packages/spectree/plugins/flask_plugin.py", line 222, in validate
    response = make_response(err.errors(), 500)
  File "/home/ncotlar/MF/venv/lib/python3.10/site-packages/flask/helpers.py", line 189, in make_response
    return current_app.make_response(args)  # type: ignore
  File "/home/ncotlar/MF/venv/lib/python3.10/site-packages/flask/app.py", line 1730, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a list.
```

### To Reproduce

Set up a Flask application to return a data structure that does not match the specified pydantic model
example:
```python
from flask import Flask
from pydantic import BaseModel
from spectree import SpecTree, Response


class TestResponse(BaseModel):
    name: str
    age: int

app = Flask(__name__)
spec = SpecTree("flask", app=app, title="Test Service Spec")

@app.route("/test")
@spec.validate(resp=Response(HTTP_200=TestResponse))
def test():
    test_response_dict = {
        "name": "test",
        "age": "yoyo"
    }
    return test_response_dict


if __name__ == "__main__":
    app.run(debug=True, port=5555, host="0.0.0.0")
```
and call with `curl` or something:
`curl localhost:5555/test`

### Expected behavior

In the past, a response with a `500` status code was returned with the content:
```json
{
  "message": "response validation error"
}
```
i suppose this is the expected behavior.

### The spectree version

```
ncotlar@mfnosson ~/MF$ pip show spectree; uname -a; python --version
Name: spectree
Version: 1.2.4
Summary: generate OpenAPI document and validate request&response with Python annotations.
Home-page: 
Author: 
Author-email: Keming Yang <kemingy94@gmail.com>
License: Apache-2.0
Location: /home/ncotlar/MF/venv/lib/python3.10/site-packages
Requires: pydantic
Required-by: 
Linux mfnosson 5.15.0-1030-aws #34-Ubuntu SMP Mon Jan 23 20:13:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
Python 3.10.12
```

### Additional context

this appears to have begun in the most recent version, `1.2.4`

**Comment by nossonCotlar** [comment]
after some more testing, i see that the issue stemmed from the version of Flask i was using (`2.1.3`), which was not able to return lists natively.
I have updated to `Flask==2.3.3` and it works fine. Closing. Apologies for the false alarm.
